# In-Class Programming Activity, Day 8

Your work goes here ...

### Task 1

```{r}
x = runif(100, min = 20, max = 70)
y = 5 + 3*x + 2*rnorm(100)
My_data = data.frame(x, y)
plot(My_data)
LL_line = function(params) {
  stopifnot(length(params) == 3)
  m = params[1]
  b = params[2]
  sigma = params[3]
  return(sum(log(dnorm(y - (m * x + b), sd = sigma))))
}
testA = LL_line(c(3, 5, 2))
testB = LL_line(c(4, 1, 10))
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control=list(fnscale = -1))
```
### Task 2

```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
attach(Taxi_trips)
```


```{r}
taxi_likelihood = function(function_params) {
  stopifnot(length(function_params) == 3)
  base_fare = function_params["base_fare"]
  per_mile = function_params["per_mile"]
  params = function_params["params"]
  
  waiting_fare <- sum(log(dexp(fare_amount - (base_fare + per_mile*trip_distance), params) +.0001))
  return(waiting_fare)
}
test = c(base_fare = 2.00, per_mile = 4.00, params = 1/3)
best <- optim(test, taxi_likelihood, control = list(fnscale = -1))
plot(trip_distance, fare_amount)
abline(best$par['base_fare'], best$par['per_mile'])
```



## Test statements

```{r}
scoreActivity::score253(8)
```